-- Grant NT AUTHORITY\SYSTEM read access to MEGAPLUS databases.
-- Run once with admin rights. Idempotent — safe to re-run.

USE master;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'NT AUTHORITY\SYSTEM')
    CREATE LOGIN [NT AUTHORITY\SYSTEM] FROM WINDOWS;
GO

USE MEGAPLUS_1329;
GO
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'NT AUTHORITY\SYSTEM')
    CREATE USER [NT AUTHORITY\SYSTEM] FOR LOGIN [NT AUTHORITY\SYSTEM];
GO
ALTER ROLE db_datareader ADD MEMBER [NT AUTHORITY\SYSTEM];
GO

USE MEGAPLUS_1301;
GO
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'NT AUTHORITY\SYSTEM')
    CREATE USER [NT AUTHORITY\SYSTEM] FOR LOGIN [NT AUTHORITY\SYSTEM];
GO
ALTER ROLE db_datareader ADD MEMBER [NT AUTHORITY\SYSTEM];
GO

PRINT 'Done. NT AUTHORITY\SYSTEM has db_datareader on MEGAPLUS_1329 and MEGAPLUS_1301.';
